name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install DistributionTool.exe
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://developer.elgato.com/documentation/stream-deck/distributiontool/DistributionToolWindows.zip" -OutFile "DistributionToolWindows.zip"
          Expand-Archive "DistributionToolWindows.zip"
      - name: Build Plugin
        shell: pwsh
        run: |
          Remove-Item Release\*
          mkdir -Force Release
          DistributionToolWindows/DistributionTool.exe -b -i Sources/net.nikjohnson.hll-computer.sdPlugin -o Release
      - name: Create a Release
        if: ${{ success() }}
        shell: pwsh
        run: |
          hub release create -d -a "Release/net.nikjohnson.hll-computer.streamDeckPlugin" -m "${{ github.ref_name }}" "${{ github.ref }}"
